# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
testRead <- function(fileName, simTime, numPatch, genotypes) {
    .Call('_fwritetest_testRead', PACKAGE = 'fwritetest', fileName, simTime, numPatch, genotypes)
}

#' @export
S_A <- function(outputFiles, maleFiles, femaleFiles, simTime, numPatch, genotypes) {
    invisible(.Call('_fwritetest_S_A', PACKAGE = 'fwritetest', outputFiles, maleFiles, femaleFiles, simTime, numPatch, genotypes))
}

#' @export
M_Q <- function(writeDir, maleFiles, femaleFiles, doMean, doQuant, quantiles, numReps, simTime, numPatch, genotypes) {
    invisible(.Call('_fwritetest_M_Q', PACKAGE = 'fwritetest', writeDir, maleFiles, femaleFiles, doMean, doQuant, quantiles, numReps, simTime, numPatch, genotypes))
}

#' @export
NEWANALYSIS <- function(maleNames, femaleNames, doMean, doQuant, quantiles, colNames, eol, maleData, femaleData) {
    invisible(.Call('_fwritetest_NEWANALYSIS', PACKAGE = 'fwritetest', maleNames, femaleNames, doMean, doQuant, quantiles, colNames, eol, maleData, femaleData))
}

rcpparma_hello_world <- function() {
    .Call('_fwritetest_rcpparma_hello_world', PACKAGE = 'fwritetest')
}

rcpparma_outerproduct <- function(x) {
    .Call('_fwritetest_rcpparma_outerproduct', PACKAGE = 'fwritetest', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_fwritetest_rcpparma_innerproduct', PACKAGE = 'fwritetest', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_fwritetest_rcpparma_bothproducts', PACKAGE = 'fwritetest', x)
}

