# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
testRead <- function(fileName, simTime, numPatch, genotypes) {
    .Call('_fwritetest_testRead', PACKAGE = 'fwritetest', fileName, simTime, numPatch, genotypes)
}

#' @export
Split_Aggregate <- function(outputFiles, maleFiles, femaleFiles, simTime, numPatch, genotypes) {
    invisible(.Call('_fwritetest_Split_Aggregate', PACKAGE = 'fwritetest', outputFiles, maleFiles, femaleFiles, simTime, numPatch, genotypes))
}

#' @export
Mean_Quantiles <- function(maleNames, femaleNames, doMean, doQuant, quantiles, colNames, eol, maleData, femaleData) {
    invisible(.Call('_fwritetest_Mean_Quantiles', PACKAGE = 'fwritetest', maleNames, femaleNames, doMean, doQuant, quantiles, colNames, eol, maleData, femaleData))
}

rcpparma_hello_world <- function() {
    .Call('_fwritetest_rcpparma_hello_world', PACKAGE = 'fwritetest')
}

rcpparma_outerproduct <- function(x) {
    .Call('_fwritetest_rcpparma_outerproduct', PACKAGE = 'fwritetest', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_fwritetest_rcpparma_innerproduct', PACKAGE = 'fwritetest', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_fwritetest_rcpparma_bothproducts', PACKAGE = 'fwritetest', x)
}

